version: "3"

services:
  client:
    build: ./client
    ports:
      - "80:80"
  server:
    build: ./server
    ports:
      - "3000:3000"
    depends_on:
      - mongo
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
