const TASK_TITLE_MIN_LENGHT = 3;
const TASK_TITLE_MAX_LENGHT = 25;

const TASK_MIN_POINTS = 1;
const TASK_MAX_POINTS = 100;


module.exports = {
    TASK_TITLE_MIN_LENGHT,
    TASK_TITLE_MAX_LENGHT,
    TASK_MIN_POINTS,
    TASK_MAX_POINTS
}